"""Add intelligence and chunks schema

Revision ID: 3d8cd5fc6faf
Revises: b0f15d2cab0a
Create Date: 2026-06-28 10:49:43.421224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8cd5fc6faf'
down_revision = 'b0f15d2cab0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extraction_status', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('extraction_error', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extracted_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('extraction_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extraction_method')
    op.drop_column('documents', 'extracted_at')
    op.drop_column('documents', 'extraction_error')
    op.drop_column('documents', 'extraction_status')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'description')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
